version: '3.8'

services:
  app:
    build:
      context: .
      args:
        PORT: ${PORT:-80}
    container_name: wechat-saoche
    ports:
      - "${PORT:-80}:${PORT:-80}"
    env_file:
      - .env
    restart: always
    volumes:
      - ./userData.json:/app/userData.json
